# Generated by Django 3.1.7 on 2021-03-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.CharField(max_length=15)),
                ('agency_branch', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('user_id', 'email')},
            },
        ),
    ]
