# Generated by Django 3.1.7 on 2021-04-07 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crimereports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_id', models.IntegerField(db_column='Crime ID', unique=True)),
                ('location_of_crime', models.TextField(db_column='Location of Crime')),
                ('type_of_crime', models.CharField(db_column='Type of Crime', max_length=50)),
                ('date_of_crime', models.CharField(db_column='Date of Crime', max_length=10)),
                ('crime_description', models.TextField(db_column='Crime Description')),
                ('user', models.ForeignKey(db_column='User ID', on_delete=django.db.models.deletion.CASCADE, to='user.genuser')),
            ],
        ),
    ]
