# Generated by Django 3.1.7 on 2021-03-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crimereports',
            fields=[
                ('nid', models.IntegerField(db_column='NID')),
                ('crime_id', models.IntegerField(db_column='Crime ID', primary_key=True, serialize=False)),
                ('location_of_crime', models.TextField(db_column='Location of Crime')),
                ('type_of_crime', models.TextField(db_column='Type of Crime')),
                ('date_of_crime', models.CharField(db_column='Date of Crime', max_length=10)),
            ],
        ),
    ]
