# Generated by Django 3.1.7 on 2021-05-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimereports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimereports',
            name='crime_id',
        ),
    ]
