# Generated by Django 3.1.7 on 2021-04-07 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.IntegerField(db_column='NID', unique=True)),
                ('home_address', models.TextField(db_column='Home Address')),
                ('gender', models.CharField(db_column='Gender', max_length=10)),
                ('mobile_number', models.CharField(db_column='Mobile Number', max_length=15, unique=True)),
                ('user', models.OneToOneField(db_column='User ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
