# Generated by Django 3.1.7 on 2021-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='First Name', max_length=20)),
                ('last_name', models.CharField(db_column='Last Name', max_length=20)),
                ('nid', models.IntegerField(db_column='NID')),
                ('email', models.TextField(db_column='Email Address')),
                ('home_address', models.TextField(db_column='Home Address')),
                ('gender', models.CharField(db_column='Gender', max_length=10)),
                ('mobile_number', models.CharField(db_column='Mobile Number', max_length=15)),
                ('password', models.CharField(db_column='Password', max_length=15)),
            ],
            options={
                'unique_together': {('nid', 'email', 'mobile_number')},
            },
        ),
    ]
