# Generated by Django 3.1.7 on 2021-03-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(db_column='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_column='First Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(db_column='Gender', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='home_address',
            field=models.TextField(db_column='Home Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(db_column='Last Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(db_column='Mobile Number', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='nid',
            field=models.IntegerField(db_column='NID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='Password', max_length=15),
        ),
    ]
